In [1]:
import numpy as np

In [2]:
a = [1,2,3,4]
print(a, type(a))

[1, 2, 3, 4] <class 'list'>


In [6]:
arr = np.array([1,2,3,4,5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [10]:
zeroarra = np.zeros((3,3))
print(zeroarra)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
onearra = np.ones((3,3))
print(onearra)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
rand_arr = np.random.rand(5,5)
print(rand_arr)

[[0.73721069 0.63078399 0.47031727 0.62915397 0.55262777]
 [0.27070571 0.17762534 0.10170853 0.57949933 0.23023277]
 [0.73101569 0.59434106 0.90214229 0.53237406 0.57114942]
 [0.78259567 0.07210574 0.3670751  0.92041182 0.87113152]
 [0.1997471  0.17965477 0.24411145 0.42165601 0.44645048]]


In [17]:
arr = np.array([1,2,3,4,5], ndmin=3)
print(arr)
print(arr.shape)
print(arr[0])
print(arr[0])

[[[1 2 3 4 5]]]
(1, 1, 5)
[[1 2 3 4 5]]
[[1 2 3 4 5]]


In [18]:
import pandas as pd

In [19]:
data = [10, 20, 30, 40, 50]
series_from_list = pd.Series(data)
print(series_from_list)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [5]:
import pandas as pd

data_list = [['Dikshit', 23], ['Bob', 23], ['aline', 25]]
df_from_list = pd.DataFrame(data_list)
print(df_from_list)

         0   1
0  Dikshit  23
1      Bob  23
2    aline  25
